### PR TITLE
FI-2723 Fix backend services discovery test versioning error

### LINKED ISSUE #23: Bulk Export V1 using smart app launch V2
Hi there,

I was just attempting to run the bulk export v1.0.1 tests against a development server and noticed it was running tests specific to SMART App Launch V2. This server is conformant to the currently active g10 regulations, for which Smart V1 is the current requirement. It would be nice to be able to run the bulk export tests with Smart V1 instead. 

Specifically the server failed on the "grant_types_supported" requirement on the well-known smart configuration because that was an addition in Smart V2. We plan to support that before the deadline, but we have not implemented support for it yet.

### PR DESCRIPTION
**Pull request by alisawallace**
# Summary
Fixes #23 

This PR fixes the issue in which the Bulk Data V1 SMART Backend Services tests were using [Discovery Tests for SMART STU2](https://hl7.org/fhir/smart-app-launch/STU2/conformance.html).  V1 Discovery Tests have been updated to reflect the requirements in the [Bulk Data V1 SMART Backend Services Authorization profile](https://hl7.org/fhir/uv/bulkdata/STU1.0.1/authorization/index.html#advertising-server-conformance-with-smart-backend-services), including:
- Ungrouping the SMART Backend Services tests so that SMART Backend Services Authorization tests can be run without Discovery tests (to reflect that use of the well-known endpoint/discovery tests is a MAY, not a SHALL)
- Checking the discovery metadata contents for all of the recommended fields.  Though inclusion of all of these fields is a SHOULD, the (optional) metadata contents test requires a correct `token_endpoint` entry to pass.  This is for two reasons:
     1. The `token_endpoint` value is used in downstream tests
     2. The `token_endpoint` value is the only one listed in the Bulk Data V1 IG that is also required in the [SMART App Launch STU1 discovery/capabilities](https://www.hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#using-well-known).

All other recommended fields tested issue warnings rather than failing the tests.

Bulk Data V2 tests are unchanged.

# Testing Guidance

Tests can be run locally - select the Bulk Data Access V1.0.1 suite and use the Inferno Reference server preset.
Spec test included for the new test.

### CODE REVIEW

File: spec/bulk_data_test_kit/bulk_data_smart_discovery_v1_contents_test_spec.rb [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+      result = run(runnable, well_known_configuration: JSON.generate(metadata))
+      expect(result.result).to eq('pass')
+    end
+  end
+
+  it 'fails when token_endpoint field is missing' do
+    metadata = correct_metadata
+    metadata.delete('token_endpoint')
+    result = run(runnable, well_known_configuration: JSON.generate(metadata))
+    expect(result.result).to eq('fail')
```
Comment (emichaud998) [inline spec/bulk_data_test_kit/bulk_data_smart_discovery_v1_contents_test_spec.rb:64]: Any test that you are checking if it fails should also check that the result message (result.result_message) is what you are expecting to make sure it is failing for the right reason

**Review by esemple998 — CHANGES_REQUESTED** [review]

File: lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_backend_services_v1_group.rb [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+      title 'SMART Backend Services'
+      id :bulk_data_smart_backend_services_v101
+      optional
+
+      group from: :bulk_data_smart_discovery_v1,
+            config: {
+              inputs: { url: { name: :bulk_server_url } }
+            }
+
+      group from: :backend_services_authorization
```
[the remark this answers is not in the document]
Comment (alisawallace) [reply lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_backend_services_v1_group.rb:18]: I agree with you!  That's what I originally had hoped to do, but I cannot get it to work in this test kit.  I've tried adding run as group to line 17, before the `group from: :backend_services_authorization`, and well as adding a config setting: `group from: :backend_services_authorization, config { options: run_as_group }`.  

Both result in the discovery tests AND the auth tests being grouped together, which we specifically don't want to do here since the auth tests need to be able to run without the discovery tests to conform to the requirements.  Since the `backend_services_authorization` group is imported from smart app launch, I'm wondering if the `run_as_group` needs to be added to that file in the other test kit, but I'm not always sure how the scope works with grouping and if that would have the intended result (I believe it would require a new release of the smart app launch test kit with the update to show up here as well).  

If you have other ideas let me know!  If not, we may have to let it slide.

[the remark this answers is not in the document]
Comment (emichaud998) [reply lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_backend_services_v1_group.rb:18]:
```suggestion
      group from: :backend_services_authorization,
      run_as_group:true
```

[the remark this answers is not in the document]
Comment (emichaud998) [reply lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_backend_services_v1_group.rb:18]: Try the suggestion above, I think that will do it!

[the remark this answers is not in the document]
Comment (alisawallace) [reply lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_backend_services_v1_group.rb:18]: Yes thank you, that worked!  Somehow I never learned that specific syntax but now I know!

File: spec/bulk_data_test_kit/bulk_data_smart_discovery_v1_contents_test_spec.rb (hunk 1 above)
Comment (alisawallace) [reply spec/bulk_data_test_kit/bulk_data_smart_discovery_v1_contents_test_spec.rb:64]: Thanks, checked for the results messages in both the failure cases!

**Review by esemple998 — APPROVED** [review]
Looks good to me, but I don't have as much of a background with the SMART app launch requirements, so it is probably worth Steve taking a look at the bulk_data_smart_discovery_v1_contents_test especially

File: lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+        assert config[key].is_a?(type), "Well-known `#{key}` must be type: #{type.to_s.downcase}"
+      end
+
+      run do
+        config = JSON.parse(well_known_configuration)
+
+        # token_endpoint must be output for downstream tests to work
+        test_key(config, 'token_endpoint', String)
+        token_endpoint = config['token_endpoint']
+        assert token_endpoint.match?(URI::DEFAULT_PARSER.make_regexp), "`#{token_endpoint}` is not a valid URI"
```
Comment (Jammjammjamm) [inline lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb:35]: We have `assert_valid_http_uri` for this.

File: lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+
+        recommended_capabilities = [
+          'token_endpoint_auth_methods_supported',
+          'token_endpoint_auth_signing_alg_values_supported',
+          'scopes_supported'
+        ]
+
+        warning do
+          recommended_capabilities.each do |key|
+            test_key(config, key, Array)
```
Comment (Jammjammjamm) [inline lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb:47]: I don't think this is exactly right, because the conformance language indicates that it is not required for the fields to be present, but I think they still have to be the proper format if they are present.

**Review by Jammjammjamm — COMMENTED** [review]
It's weird to use `v1/v2` in some places and `v101/v200` in others.

File: lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb (hunk 3 above)
Comment (alisawallace) [reply lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb]: Fixed!

File: lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb (hunk 4 above)
Comment (alisawallace) [reply lib/bulk_data_test_kit/v1.0.1/bulk_data_smart_discovery_v1_contents_test.rb]: Alright, I updated the test to check which recommended capabilities are present (and warn for any that aren't present). For the entries that are present the test does a pass/fail assertion on the format and contents.  Spec test updated as well.

**Comment by alisawallace** [comment]
@Jammjammjamm I updated all of the versioning syntax to be consistent with vXXX and responded to both of your comments, so requesting re-review.

**Review by Jammjammjamm — APPROVED** [review]
